idf_component_register(
    SRCS "human_display.c"
         "human/mage/human_mage_caststaff_1.c"
         "human/mage/human_mage_caststaff_2.c"
         "human/mage/human_mage_caststaff_3.c"
         "human/mage/human_mage_caststaff_4.c"
         "human/mage/human_mage_caststaff_5.c"
         "human/mage/human_mage_caststaff_6.c"
         "human/mage/human_mage_roll_1.c"
         "human/mage/human_mage_roll_2.c"
         "human/mage/human_mage_roll_3.c"
         "human/mage/human_mage_roll_4.c"
         "human/mage/human_mage_roll_5.c"
         "human/mage/human_mage_roll_6.c"
         "human/mage/human_mage_walk_1.c"
         "human/mage/human_mage_walk_2.c"
         "human/mage/human_mage_walk_3.c"
         "human/mage/human_mage_walk_4.c"
         "human/mage/human_mage_walk_5.c"
         "human/mage/human_mage_walkfront_1.c"
         "human/mage/human_mage_walkfront_2.c"
         "human/mage/human_mage_walkfront_3.c"
         "human/mage/human_mage_walkfront_4.c"
         "human/mage/human_mage_walkfront_5.c"
    INCLUDE_DIRS "."
    REQUIRES lvgl
)
